// Database for Cards and Localization Language Strings

const cardsData = [
    {
        id: "A",
        name: "Bugatti Veyron 16.4",
        category: "A/1",
        country: "🇫🇷",
        image: "A.png",
        rarity: "legendary",
        superTrumpf: true,
        stats: {
            baujahr: { value: 2005, unit: "", label: "Baujahr", higherIsBetter: false },
            motor: { value: "W16-Quadturbo", raw: 16, unit: "", label: "Motor", higherIsBetter: true },
            hubraum: { value: 7993, unit: "ccm", label: "Hubraum", higherIsBetter: true },
            leistung: { value: 1001, unit: "PS", label: "Leistung", higherIsBetter: true },
            max_speed: { value: 407, unit: "km/h", label: "Höchstgeschwindigkeit", higherIsBetter: true },
            acceleration: { value: 2.5, unit: "Sek", label: "0-100 km/h", higherIsBetter: false },
            production: { value: 450, unit: "Stk", label: "Produktionszahlen", higherIsBetter: false },
            value_euro: { value: 1800000, unit: "€", label: "Wert", higherIsBetter: true }
        }
    },
    {
        id: "B",
        name: "Mercedes-Benz 300 SL",
        category: "B/1",
        country: "🇩🇪",
        image: "B.png",
        rarity: "legendary",
        superTrumpf: false,
        stats: {
            baujahr: { value: 1954, unit: "", label: "Baujahr", higherIsBetter: false },
            motor: { value: "Reihen-6", raw: 6, unit: "", label: "Motor", higherIsBetter: true },
            hubraum: { value: 2996, unit: "ccm", label: "Hubraum", higherIsBetter: true },
            leistung: { value: 215, unit: "PS", label: "Leistung", higherIsBetter: true },
            max_speed: { value: 260, unit: "km/h", label: "Höchstgeschwindigkeit", higherIsBetter: true },
            acceleration: { value: 8.9, unit: "Sek", label: "0-100 km/h", higherIsBetter: false },
            production: { value: 1400, unit: "Stk", label: "Produktionszahlen", higherIsBetter: false },
            value_euro: { value: 1500000, unit: "€", label: "Wert", higherIsBetter: true }
        }
    },
    {
        id: "c",
        name: "Porsche 911 Carrera RS",
        category: "C/1",
        country: "🇩🇪",
        image: "c.png",
        rarity: "rare",
        superTrumpf: false,
        stats: {
            baujahr: { value: 1973, unit: "", label: "Baujahr", higherIsBetter: false },
            motor: { value: "Boxer-6", raw: 6, unit: "", label: "Motor", higherIsBetter: true },
            hubraum: { value: 2687, unit: "ccm", label: "Hubraum", higherIsBetter: true },
            leistung: { value: 210, unit: "PS", label: "Leistung", higherIsBetter: true },
            max_speed: { value: 245, unit: "km/h", label: "Höchstgeschwindigkeit", higherIsBetter: true },
            acceleration: { value: 5.8, unit: "Sek", label: "0-100 km/h", higherIsBetter: false },
            production: { value: 1580, unit: "Stk", label: "Produktionszahlen", higherIsBetter: false },
            value_euro: { value: 800000, unit: "€", label: "Wert", higherIsBetter: true }
        }
    },
    {
        id: "D",
        name: "Ferrari F40",
        category: "D/1",
        country: "🇮🇹",
        image: "D.png",
        rarity: "legendary",
        superTrumpf: true,
        stats: {
            baujahr: { value: 1987, unit: "", label: "Baujahr", higherIsBetter: false },
            motor: { value: "V8-Biturbo", raw: 8, unit: "", label: "Motor", higherIsBetter: true },
            hubraum: { value: 2936, unit: "ccm", label: "Hubraum", higherIsBetter: true },
            leistung: { value: 478, unit: "PS", label: "Leistung", higherIsBetter: true },
            max_speed: { value: 324, unit: "km/h", label: "Höchstgeschwindigkeit", higherIsBetter: true },
            acceleration: { value: 4.1, unit: "Sek", label: "0-100 km/h", higherIsBetter: false },
            production: { value: 1311, unit: "Stk", label: "Produktionszahlen", higherIsBetter: false },
            value_euro: { value: 2500000, unit: "€", label: "Wert", higherIsBetter: true }
        }
    },
    {
        id: "E",
        name: "Lamborghini Countach",
        category: "E/1",
        country: "🇮🇹",
        image: "E.png",
        rarity: "rare",
        superTrumpf: false,
        stats: {
            baujahr: { value: 1974, unit: "", label: "Baujahr", higherIsBetter: false },
            motor: { value: "V12", raw: 12, unit: "", label: "Motor", higherIsBetter: true },
            hubraum: { value: 3929, unit: "ccm", label: "Hubraum", higherIsBetter: true },
            leistung: { value: 375, unit: "PS", label: "Leistung", higherIsBetter: true },
            max_speed: { value: 309, unit: "km/h", label: "Höchstgeschwindigkeit", higherIsBetter: true },
            acceleration: { value: 5.4, unit: "Sek", label: "0-100 km/h", higherIsBetter: false },
            production: { value: 1983, unit: "Stk", label: "Produktionszahlen", higherIsBetter: false },
            value_euro: { value: 900000, unit: "€", label: "Wert", higherIsBetter: true }
        }
    },
    {
        id: "F",
        name: "VW Käfer (Beetle)",
        category: "F/1",
        country: "🇩🇪",
        image: "F.png",
        rarity: "uncommon",
        superTrumpf: false,
        stats: {
            baujahr: { value: 1938, unit: "", label: "Baujahr", higherIsBetter: false },
            motor: { value: "Boxer-4", raw: 4, unit: "", label: "Motor", higherIsBetter: true },
            hubraum: { value: 1192, unit: "ccm", label: "Hubraum", higherIsBetter: true },
            leistung: { value: 30, unit: "PS", label: "Leistung", higherIsBetter: true },
            max_speed: { value: 110, unit: "km/h", label: "Höchstgeschwindigkeit", higherIsBetter: true },
            acceleration: { value: 38.0, unit: "Sek", label: "0-100 km/h", higherIsBetter: false },
            production: { value: 21529464, unit: "Stk", label: "Produktionszahlen", higherIsBetter: false },
            value_euro: { value: 25000, unit: "€", label: "Wert", higherIsBetter: true }
        }
    },
    {
        id: "G",
        name: "McLaren F1",
        category: "G/1",
        country: "🇬🇧",
        image: "G.png",
        rarity: "legendary",
        superTrumpf: true,
        stats: {
            baujahr: { value: 1993, unit: "", label: "Baujahr", higherIsBetter: false },
            motor: { value: "V12", raw: 12, unit: "", label: "Motor", higherIsBetter: true },
            hubraum: { value: 6064, unit: "ccm", label: "Hubraum", higherIsBetter: true },
            leistung: { value: 627, unit: "PS", label: "Leistung", higherIsBetter: true },
            max_speed: { value: 386, unit: "km/h", label: "Höchstgeschwindigkeit", higherIsBetter: true },
            acceleration: { value: 3.2, unit: "Sek", label: "0-100 km/h", higherIsBetter: false },
            production: { value: 106, unit: "Stk", label: "Produktionszahlen", higherIsBetter: false },
            value_euro: { value: 15000000, unit: "€", label: "Wert", higherIsBetter: true }
        }
    },
    {
        id: "H",
        name: "Nissan Skyline GT-R R34",
        category: "H/1",
        country: "🇯🇵",
        image: "H.png",
        rarity: "rare",
        superTrumpf: false,
        stats: {
            baujahr: { value: 1999, unit: "", label: "Baujahr", higherIsBetter: false },
            motor: { value: "R6-Biturbo", raw: 6, unit: "", label: "Motor", higherIsBetter: true },
            hubraum: { value: 2568, unit: "ccm", label: "Hubraum", higherIsBetter: true },
            leistung: { value: 280, unit: "PS", label: "Leistung", higherIsBetter: true },
            max_speed: { value: 250, unit: "km/h", label: "Höchstgeschwindigkeit", higherIsBetter: true },
            acceleration: { value: 4.9, unit: "Sek", label: "0-100 km/h", higherIsBetter: false },
            production: { value: 11590, unit: "Stk", label: "Produktionszahlen", higherIsBetter: false },
            value_euro: { value: 150000, unit: "€", label: "Wert", higherIsBetter: true }
        }
    }
];

const langDict = {
    en: {
        app_title: "AUTO QUARTETT",
        label_level: "Level",
        menu_play_ai: "Play vs AI",
        menu_multiplayer: "Multiplayer",
        menu_garage: "My Garage",
        menu_high_scores: "High Scores",
        game_title: "Game Table vs AI",
        player: "Player",
        your_turn: "Your Turn",
        ai_turn: "AI Turn",
        choose_stat: "Choose your stat:",
        action_play: "Play",
        garage_title: "MY GARAGE",
        garage_subtitle: "Your Car Collection",
        unlocked: "Unlocked",
        filter_all: "All",
        filter_uncommon: "Uncommon",
        filter_rare: "Rare",
        filter_legendary: "Legendary",
        leaderboard_title: "Global Leaderboard",
        tab_global: "Global",
        tab_friends: "Friends",
        nav_home: "Home",
        nav_collection: "Collection",
        nav_leaderboard: "Leaderboard",
        nav_settings: "Settings",
        settings_title: "SETTINGS",
        settings_general: "General",
        setting_music: "Music",
        setting_sfx: "SFX",
        settings_gameplay: "Gameplay",
        setting_animations: "Card Animations",
        setting_difficulty: "AI Difficulty",
        diff_easy: "Easy",
        diff_normal: "Normal",
        diff_hard: "Hard",
        settings_language: "Game Language",
        btn_help: "Help",
        btn_terms: "Terms",
        btn_close: "Close"
    },
    de: {
        app_title: "AUTO QUARTETT",
        label_level: "Stufe",
        menu_play_ai: "Gegen KI",
        menu_multiplayer: "Mehrspieler",
        menu_garage: "Meine Garage",
        menu_high_scores: "Bestenlisten",
        game_title: "Spieltisch vs KI",
        player: "Spieler",
        your_turn: "Du bist dran",
        ai_turn: "KI ist dran",
        choose_stat: "Wähle deinen Wert:",
        action_play: "Spielen",
        garage_title: "MEINE GARAGE",
        garage_subtitle: "Deine Autosammlung",
        unlocked: "Freigeschaltet",
        filter_all: "Alle",
        filter_uncommon: "Ungewöhnlich",
        filter_rare: "Selten",
        filter_legendary: "Legendär",
        leaderboard_title: "Globale Bestenliste",
        tab_global: "Lokal",
        tab_friends: "Freunde",
        nav_home: "Heim",
        nav_collection: "Sammlung",
        nav_leaderboard: "Bestenliste",
        nav_settings: "Einstellungen",
        settings_title: "EINSTELLUNGEN",
        settings_general: "Allgemein",
        setting_music: "Musik",
        setting_sfx: "Effekte",
        settings_gameplay: "Spiel",
        setting_animations: "Kartenanimationen",
        setting_difficulty: "KI Schwierigkeit",
        diff_easy: "Leicht",
        diff_normal: "Normal",
        diff_hard: "Schwer",
        settings_language: "Sprache",
        btn_help: "Hilfe",
        btn_terms: "AGB",
        btn_close: "Schließen"
    },
    fr: {
        app_title: "AUTO QUARTETT",
        label_level: "Niveau",
        menu_play_ai: "Jouer vs IA",
        menu_multiplayer: "Multijoueur",
        menu_garage: "Mon Garage",
        menu_high_scores: "Meilleurs Scores",
        game_title: "Table contre IA",
        player: "Joueur",
        your_turn: "A toi de jouer",
        ai_turn: "Tour de l'IA",
        choose_stat: "Choisis une stat :",
        action_play: "Jouer",
        garage_title: "MON GARAGE",
        garage_subtitle: "Ta Collection",
        unlocked: "Débloqués",
        filter_all: "Tous",
        filter_uncommon: "Peu commun",
        filter_rare: "Rare",
        filter_legendary: "Légendaire",
        leaderboard_title: "Classement Mondial",
        tab_global: "Mondial",
        tab_friends: "Amis",
        nav_home: "Accueil",
        nav_collection: "Collection",
        nav_leaderboard: "Classement",
        nav_settings: "Paramètres",
        settings_title: "PARAMÈTRES",
        settings_general: "Général",
        setting_music: "Musique",
        setting_sfx: "Bruitages",
        settings_gameplay: "En jeu",
        setting_animations: "Animations de carte",
        setting_difficulty: "Difficulté IA",
        diff_easy: "Facile",
        diff_normal: "Normal",
        diff_hard: "Difficile",
        settings_language: "Langue",
        btn_help: "Aide",
        btn_terms: "Conditions",
        btn_close: "Fermer"
    },
    es: {
        app_title: "AUTO QUARTETT",
        label_level: "Nivel",
        menu_play_ai: "Jugar VS IA",
        menu_multiplayer: "Multijugador",
        menu_garage: "Mi Garaje",
        menu_high_scores: "Clasificación",
        game_title: "Mesa de Juego",
        player: "Jugador",
        your_turn: "Tu Turno",
        ai_turn: "Turno IA",
        choose_stat: "Elige estadística:",
        action_play: "Jugar",
        garage_title: "MI GARAJE",
        garage_subtitle: "Tu Colección de Coches",
        unlocked: "Desbloqueado",
        filter_all: "Todos",
        filter_uncommon: "Poco común",
        filter_rare: "Raro",
        filter_legendary: "Legendario",
        leaderboard_title: "Clasificación Global",
        tab_global: "Global",
        tab_friends: "Amigos",
        nav_home: "Inicio",
        nav_collection: "Colección",
        nav_leaderboard: "Clasificación",
        nav_settings: "Ajustes",
        settings_title: "AJUSTES",
        settings_general: "General",
        setting_music: "Música",
        setting_sfx: "Efectos",
        settings_gameplay: "Juego",
        setting_animations: "Animaciones de Carta",
        setting_difficulty: "Dificultad IA",
        diff_easy: "Fácil",
        diff_normal: "Normal",
        diff_hard: "Difícil",
        settings_language: "Idioma del Juego",
        btn_help: "Ayuda",
        btn_terms: "Términos",
        btn_close: "Cerrar"
    },
    ja: {
        app_title: "Auto Quartett",
        label_level: "レベル",
        menu_play_ai: "AIと対戦",
        menu_multiplayer: "マルチプレイ",
        menu_garage: "ガレージ",
        menu_high_scores: "ハイスコア",
        game_title: "ゲームテーブル",
        player: "プレイヤー",
        your_turn: "あなたのターン",
        ai_turn: "AIのターン",
        choose_stat: "ステータスを選択してください：",
        action_play: "プレイ",
        garage_title: "マイガレージ",
        garage_subtitle: "あなたのコレクション",
        unlocked: "ロック解除",
        filter_all: "すべて",
        filter_uncommon: "アンコモン",
        filter_rare: "レア",
        filter_legendary: "レジェンダリー",
        leaderboard_title: "グローバルリーダーボード",
        tab_global: "グローバル",
        tab_friends: "フレンド",
        nav_home: "ホーム",
        nav_collection: "コレクション",
        nav_leaderboard: "ランキング",
        nav_settings: "設定",
        settings_title: "設定",
        settings_general: "一般",
        setting_music: "音楽",
        setting_sfx: "効果音",
        settings_gameplay: "ゲームプレイ",
        setting_animations: "カードアニメーション",
        setting_difficulty: "AI難易度",
        diff_easy: "簡単",
        diff_normal: "普通",
        diff_hard: "難しい",
        settings_language: "言語",
        btn_help: "ヘルプ",
        btn_terms: "規約",
        btn_close: "閉じる"
    },
    ko: {
        app_title: "오토 콰르테트",
        label_level: "레벨",
        menu_play_ai: "AI와 대결",
        menu_multiplayer: "멀티플레이어",
        menu_garage: "내 차고",
        menu_high_scores: "최고 점수",
        game_title: "게임 테이블",
        player: "플레이어",
        your_turn: "당신 차례입니다",
        ai_turn: "AI 차례입니다",
        choose_stat: "능력치 선택:",
        action_play: "플레이",
        garage_title: "내 차고",
        garage_subtitle: "나의 자동차 컬렉션",
        unlocked: "잠금해제됨",
        filter_all: "전체",
        filter_uncommon: "언커먼",
        filter_rare: "레어",
        filter_legendary: "전설",
        leaderboard_title: "글로벌 랭킹",
        tab_global: "글로벌",
        tab_friends: "친구",
        nav_home: "홈",
        nav_collection: "컬렉션",
        nav_leaderboard: "랭킹",
        nav_settings: "설정",
        settings_title: "설정",
        settings_general: "일반",
        setting_music: "음악",
        setting_sfx: "효과음",
        settings_gameplay: "게임플레이",
        setting_animations: "카드 애니메이션",
        setting_difficulty: "AI 난이도",
        diff_easy: "쉬움",
        diff_normal: "보통",
        diff_hard: "어려움",
        settings_language: "언어",
        btn_help: "도움말",
        btn_terms: "약관",
        btn_close: "닫기"
    }
};
